pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                git(
                    url: 'https://github.com/YOUR_GITHUB_USERNAME/alx-backend-python.git',
                    credentialsId: 'github-creds'
                )
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r messaging_app/requirements.txt
                pip install pytest
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                cd messaging_app
                pytest --junitxml=pytest-report.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'messaging_app/pytest-report.xml'
        }
    }
}
